// <auto-generated />
using System;
using FullToDoWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FullToDoWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FullToDoWebsite.Models.ToDoTasks", b =>
                {
                    b.Property<int>("Task_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Task_id"), 1L, 1);

                    b.Property<DateTime>("Task_DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Task_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Task_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Task_todo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Task_id");

                    b.ToTable("todoTask");
                });
#pragma warning restore 612, 618
        }
    }
}
